### ISSUE TITLE
QPB Version 1.3b error Loop?

### ISSUE THREAD

**Issue by imsonub** [fededevi/QuickPokeBot#1]
![image](https://cloud.githubusercontent.com/assets/20704101/17276663/75269010-56e4-11e6-8c42-38d6a797cbbb.png)
I keep getting this regardless what long and lat I put

**Comment by SilentWarp** [comment]
I think something in the API has changed ans the bot is unable to find anything. I would just wait for a while to see if they fix this. Other bots are working too so I am not sure

**Comment by fededevi** [comment]
Working for me

**Comment by imsonub** [comment]
@fededevi it's fine it  started working again randomly.

**Comment by imsonub** [comment]
@fededevi Please close.
