### ISSUE TITLE
Add new version pls

### ISSUE THREAD

**Issue by ReiPlayGamesPL** [fededevi/QuickPokeBot#10]
Add to Whitelist new version , pokemon no transfer lists etc
Pls

**Comment by imsonub** [comment]
Since someone made a new Issue I dont want to make one and be a hassle i'll just reply to this one.
@fededevi Did I do good on the Post with the Update?
http://www.mpgh.net/forum/showthread.php?t=1147351

**Comment by Zvonja** [comment]
Yep whitelist please
