### ISSUE TITLE
Where do I open new requests?

### ISSUE THREAD

**Issue by Zvonja** [fededevi/QuickPokeBot#11]
Pretty noob with GitHub... :)

EDIT: Why would I like to evolve useless pokemons?

**Comment by imsonub** [comment]
Fededevi. Think you'd know how this guy got this to work?
https://www.youtube.com/watch?v=8P2tb-1_Uy8
Also @Zvonja Join the Discord! https://discord.gg/8c7e8sQ

**Comment by imsonub** [comment]
@fededevi Going to update the threads on MPGH,Epvp,UnknownCheats after I finish streaming
I'll make a new video for it alright?

**Comment by fededevi** [comment]
That bot is sweet! But as  it is more important to -level up first- then search for nice pokemons, You don't need 100cp Snorlaxes. Anyway do wathever on the forums, I don't care :D

**Comment by Zvonja** [comment]
@fededevi You didn't answer my questions?

**Comment by fededevi** [comment]
you get 500 exp for each evolve, so 500 more exp every 4 pidgeys/weedle and so on

**Comment by Zvonja** [comment]
but you waste stardust?

Could you add option to disable that?
And whitelist would be really nice cause I play with Vaporeon/Dragonite , and I want to have more than 1 so I can capture more gyms...

**Comment by fededevi** [comment]
No it does not use stardust

**Comment by Zvonja** [comment]
oh sry i'm stupid lol...

and for the whitelist , pls i'd really need it
