### ISSUE TITLE
QPB stopped working

### ISSUE THREAD

**Issue by holygodz** [fededevi/QuickPokeBot#2]
Any solution ? 
![screenshot_3](https://cloud.githubusercontent.com/assets/20757203/17277848/18a1d042-5780-11e6-847a-3b5e97780fbf.png)

Win 7 x64

Thank you..

**Comment by SilentWarp** [comment]
You have put the PTC username and password in the wrong place!

`  <add key="PtcUsername" value="USERNAME HERE" />
  <add key="PtcPassword" value="PASSWORD HERE" />`

**Comment by holygodz** [comment]
My bad, sorry and thank you sir..

**Comment by Zvonja** [comment]
Close the issue if it's solved...
