### ISSUE TITLE
Error : Null Refference - Restarting

### ISSUE THREAD

**Issue by Zvonja** [fededevi/QuickPokeBot#2]
I do everything as said in the guide and start a bot , go to google.com/device and type in the code and log into google and then it just keep doing this 
![image](https://cloud.githubusercontent.com/assets/9727042/17208367/c05c2f8c-54b8-11e6-92b4-f1ccffa2e076.png)

**Comment by fededevi** [comment]
Confirmed, working on this.

**Comment by Zvonja** [comment]
I'm new to this and I didn't quite understand what you said , how do you mean "old tickets from other bots" ?

**Comment by fededevi** [comment]
It is now fixed, refer to the last release. I will update readme.md too.
