### ISSUE TITLE
google Auth/Refresh Token Location?

### ISSUE THREAD

**Issue by imsonub** [fededevi/QuickPokeBot#3]
Hey! Just saw your post on mpgh. I Downloaded it and I've read that the google servers are down or something like that. But I Have my Auth Code/Refresh Token so I dont need to Add Device. I'm just not sure where to go to add it in so I can start using the bot.

**Comment by Zvonja** [comment]
I don't know shit but i think you should make token.txt file in the folder and paste it there becuase that's what it does by itself

**Comment by fededevi** [comment]
You'll have to add password and email in external.config file. I will update readme.md too in a while.
