### ISSUE TITLE
error: " Unhandled Exception: System.Exception: NeedsBrowser "

### ISSUE THREAD

**Issue by Zvonja** [fededevi/QuickPokeBot#4]
After the google login fix I write in the email and pw and this happens...

![image](https://cloud.githubusercontent.com/assets/9727042/17222126/10f03c5c-54f7-11e6-94eb-9aa108de8aae.png)

**Comment by fededevi** [comment]
Read the readme. 

Setup Guide....
 If using 2 step authentication you can generate a new password for the bot here: https://security.google.com/settings/security/apppasswords

**Comment by Zvonja** [comment]
Thanks it's working now!
