### ISSUE TITLE
It Started very good. but now it's on loop.

### ISSUE THREAD

**Issue by imsonub** [fededevi/QuickPokeBot#6]
It's on loop now...
![232e42ff9cef4ff18a52f7df8a0fb768](https://cloud.githubusercontent.com/assets/20704101/17237180/effb1b7c-5503-11e6-9627-76f968214650.png)

**Comment by Zvonja** [comment]
Same to me

**Comment by fededevi** [comment]
Nianitc implemented a restriction on the numbe of requests / second, this means no more super fast bots.

**Comment by Zvonja** [comment]
Well slower should still be a lot better than walking around ... right?

**Comment by fededevi** [comment]
Working on it, trying to understand the fastest possible way.

**Comment by Zvonja** [comment]
Thanks a lot :)

**Comment by imsonub** [comment]
Thank you for constantly replying nonstop!

**Comment by fededevi** [comment]
Last commit is working but tested it for 5 minutes only so try it.  Play with "Task.Delay(x);" in Program.cs to optimize/fix

**Comment by Zvonja** [comment]
I can't find "Program.cs" in the folder , would you mind telling me where it is?

**Comment by Zvonja** [comment]
I think I found it but I don't think it's editable with notepad or notepad++... what program should I use to edit it?

**Comment by fededevi** [comment]
Visual Studio 2015, I will not provide any more releases

FD

**Comment by fededevi** [comment]
It is now bak to 100K/h, removed useless request & optimized
