### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ReiPlayGamesPL** [fededevi/QuickPokeBot#7]
Bot not working version 1.1

**Comment by Zvonja** [comment]
You should describe the problem and put a picture so the creator has something to work with....

**Comment by ReiPlayGamesPL** [comment]
I have this problem as you

**Comment by Zvonja** [comment]
Then close this one and use mine since mine has a picture of the problem and wait there for an answer... :)

**Comment by fededevi** [comment]
#8
