### ISSUE TITLE
Error "Something's wrong when loading language file"

### ISSUE THREAD

**Issue by Zvonja** [fededevi/QuickPokeBot#8]
When I start the bot it says "Something's wrong when loading language file"

![image](https://cloud.githubusercontent.com/assets/9727042/17247063/97a028e0-5590-11e6-8155-9c3cbebccbff.png)

EDIT: And I can't find Program.cs and "Task.Delay(x);" ...where is it? (I am using microsoft visual 2015)

**Comment by fededevi** [comment]
Fixed, redownload

**Comment by fededevi** [comment]
PS TY for the issue reporting. I appreciate. Also let me know if any more strange problem rises.
